name=ToysToLifelib
version=0.0.1
author=FromDarkHell
maintainer=Joe Iliff <fdh@fdh.one>
sentence=Arduino library for interfacing and generating Toys-to-Life USB Packets
paragraph=Arduino library for interfacing and generating Toys-to-Life USB Packets
category=Display
url=https://github.com/FromDarkHell/ToysToLifeLib
architectures=*
# includes=Adafruit_NeoPixel.h
