[platformio]
src_dir = src

[env]
framework = arduino
lib_deps =
    symlink://../..
monitor_speed = 115200


[env:esp32dev]
platform = espressif32
board = esp32dev

[env:pico2w]
board_build.filesystem = littlefs
board_build.core = earlephilhower

platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
board_build.filesystem_size = 1.5m